### ISSUE TITLE
MariaDB 10.2 extended support (meta)

### ISSUE THREAD

**Issue by belgattitude** [doctrine/dbal#2923]
Once initial MariaDB 10.2 support (#2825) has landed (2.7), some tasks can be addressed. Not an issue, but just to keep as reference.

Re-enable features (code already exists):

- [ ] JSON support. See https://github.com/doctrine/dbal/issues/3202.
- [ ] Support for BLOB/TEXT defaults. See https://github.com/doctrine/dbal/pull/4917.
- [x] Escaping of default literals (all platforms - see with #2850)

Further improvements

- [ ] Initial support for expressions (all platforms) . 

Also some notes from @morozov
> Looks like we're in agreement. To summarize, the following issues are still unresolved, but they require deeper diving into the design:
> - MySqlSchemaManager::getMariaDb1027ColumnDefault(). Given that MariaDB is a separate platform, it should have its own schema manager.
> - When the default expression represents a literal, it's parsed using string functions. This is okay as a temporary workaround but it doesn't take into account the charset and may produce unexpected results with multi-byte encodings. A proper solution would be to make default expressions first-class citizens and compare expressions to expressions without parsing.

**Comment by Majkl578** [comment]
> Once initial MariaDB 10.2 support (#2825) has landed (2.7)

Done today. :tada: 

What is the status here now?

**Comment by morozov** [comment]
Closing as most of the issues are being worked individually and this specific one hasn't been used since the time of filing.
